version: "3"
services:

  php7.2:
    tty: true
    build:
      context: .
      args:
        - PHP_VERSION=7.2
    volumes:
      - .:/var/www/html

  php7.1:
    tty: true
    build:
      context: .
      args:
        - PHP_VERSION=7.1
    volumes:
      - .:/var/www/html
