name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
      fail-fast: false
    env:
      MATRIX_PHP: ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: composer
          # PHP 7.1 development web server segfaults if timezone not set.
          ini-values: date.timezone=Europe/Berlin, error_reporting=-1, display_errors=On
      - name: Configure for PHP >= 7.2
        if: "${{ matrix.php >= '7.2' }}"
        run: |
          composer require --no-update --dev dbrekelmans/bdi
      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist
      - name: Add browser drivers for PHP >= 7.2
        if: "${{ matrix.php >= '7.2' }}"
        run: |
          vendor/bin/bdi detect drivers
      - name: Add browser drivers for PHP == 7.1
        if: "${{ matrix.php == '7.1' }}"
        # additionally, place 'chromedriver' file also in folder 'driver' for symfony/panther >=0.9 and PHP 7.1
        run: |
          bin/updatePantherChromeDriver.sh
          mkdir drivers
          mv vendor/symfony/panther/chromedriver-bin/chromedriver_linux64 drivers/chromedriver
      - name: Setup Mink test server
        # PHP 7.1 development web server segfaults if USE_ZEND_ALLOC not set to 0.
        run: |
          mkdir ./logs
          export USE_ZEND_ALLOC=0
          ./vendor/bin/mink-test-server &> ./logs/mink-test-server.log &
      - name: Run tests
        run: |
          vendor/bin/phpunit -v
      - name: Archive logs artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs_php-${{ matrix.php }}
          path: |
            logs
